# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('winner', models.CharField(blank=True, choices=[(b'white', b'white'), (b'red', b'red'), (b'orange', b'orange'), (b'yellow', b'yellow'), (b'cyan', b'cyan'), (b'green', b'green'), (b'blue', b'blue'), (b'purple', b'purple'), (b'pink', b'pink')], max_length=20, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=50, null=True)),
                ('n_votes_winner', models.IntegerField(default=0)),
                ('n_votes_total', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
