# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20160326_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittervote',
            name='tally',
            field=models.CommaSeparatedIntegerField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twittervote',
            name='log',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='twittervote',
            name='winner',
            field=models.CharField(blank=True, choices=[(b'red', b'red'), (b'orange', b'orange'), (b'yellow', b'yellow'), (b'cyan', b'cyan'), (b'green', b'green'), (b'blue', b'blue'), (b'purple', b'purple'), (b'pink', b'pink')], max_length=20, null=True),
        ),
    ]
