# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_manufacturer_id'),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_at', models.DateTimeField(db_index=True)),
                ('hex_string', models.CharField(max_length=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'valid_at',
            },
        ),
    ]
